app = "rnaseq-deseq-webapp"
primary_region = "hkg"

[build]
  dockerfile = "Dockerfile"

[env]
  HOST = "0.0.0.0"
  PORT = "8788"

[http_service]
  internal_port = 8788
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 2
